services:
  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: payload-admin
      POSTGRES_DB: payload
    ports:
      - 54322:5432
  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:4444"